# Site settings
name: 刘梦冰的个人博客
email: 2273139992@qq.com
author: 刘梦冰（May）
url: http://www.liumengbing.com
resume_site: http://www.liumengbing.com/Resume.io/
github: https://github.com/LiuMengBing/
baseurl: ""
description: 大道至简。
meta_description: 刘梦冰;个人博客;大道至简;终身学习;

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LiumengBing
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
